"""Base strategy class and signal definitions."""

from __future__ import annotations

from abc import ABC, abstractmethod
from enum import Enum
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

from algo.broker.models import OrderType
from algo.data.models import Candle

if TYPE_CHECKING:
    from algo.broker.models import Fill
    from algo.strategy.context import StrategyContext


class SignalAction(Enum):
    """Trading signal action."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class Signal(BaseModel):
    """Represents a trading signal generated by a strategy."""

    instrument: str
    action: SignalAction
    quantity: int = Field(gt=0)
    order_type: OrderType = OrderType.MARKET
    limit_price: float | None = Field(default=None, gt=0)
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {"frozen": True}


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Lifecycle:
    1. __init__() - Set strategy parameters
    2. set_context() - Inject strategy context (called by engine)
    3. on_init() - Called once before first candle
    4. on_candle() - Called for each new candle
    5. on_order_fill() - Called when an order is filled
    6. on_stop() - Called when strategy is stopped
    """

    def __init__(self, **params: Any):
        """
        Initialize strategy with parameters.

        Args:
            **params: Strategy-specific parameters
        """
        self.params = params
        self._context: StrategyContext | None = None

    @property
    def context(self) -> StrategyContext:
        """Get strategy context. Raises if not set."""
        if self._context is None:
            raise RuntimeError("Strategy context not set. Call set_context() first.")
        return self._context

    def set_context(self, context: StrategyContext) -> None:
        """
        Inject the strategy context.

        Called by the engine before on_init().
        """
        self._context = context

    def on_init(self) -> None:
        """
        Called once before the first candle is processed.

        Override to initialize indicators, state, etc.
        """
        pass

    @abstractmethod
    def on_candle(self, candle: Candle) -> Signal | list[Signal] | None:
        """
        Called for each new candle.

        Args:
            candle: The new OHLCV candle

        Returns:
            Signal, list of Signals, or None for no action
        """
        pass

    def on_order_fill(self, fill: Fill) -> None:
        """
        Called when an order placed by this strategy is filled.

        Override to track fills, update state, etc.
        """
        pass

    def on_stop(self) -> None:
        """
        Called when the strategy is stopped.

        Override to cleanup resources.
        """
        pass

    @property
    def name(self) -> str:
        """Strategy name for logging and identification."""
        return self.__class__.__name__

    @property
    def instruments(self) -> list[str]:
        """
        List of instruments this strategy trades.

        Override in subclass to specify instruments.
        Format: ["EXCHANGE:SECURITY_ID", ...]
        Example: ["NSE_EQ:1333", "NSE_FNO:43225"]
        """
        return []

    def __repr__(self) -> str:
        params_str = ", ".join(f"{k}={v}" for k, v in self.params.items())
        return f"{self.name}({params_str})"
